export const MAPPING_FIELDS: (keyof import("./types").FieldMapping)[] = [
  // Core
  "Location Number",
  "Loc Name",
  "Full Address",
  "Street",
  "City",
  "County",
  "State",
  "State Code",
  "Postal Code",
  "Country",
  "Occupancy",
  "Nature of Occupancy",
  "Construction",
  "Building Value",
  "Building Value 1",
  "Building Value 2",
  "Building Value 3",
  "Building Value 4",
  "Building Value 5",
  "Contents Value",
  "Contents Value 1",
  "Contents Value 2",
  "Contents Value 3",
  "Contents Value 4",
  "Contents Value 5",
  "Business Interruption",
  "Business Interruption 1",
  "Business Interruption 2",
  "Business Interruption 3",
  "Business Interruption 4",
  "Business Interruption 5",
  "Sprinkler Type",
  "Year Built",
  "No. of Buildings",
  "No. of Stories",
  "Square Footage",
  "Year Upgraded",
  "Roof Type",
  "Foundation Type",
  "Cladding Type",
  "Soft Story",
  "Tsunami Exposure",
  "Liquefaction Exposure",
]

export const MAPPING_ALIASES: Record<string, string[]> = {
  "Location Number": ["loc_num", "location_id", "loc_id", "location", "site_id", "property_id"],
  "Loc Name": ["location_name", "property_name", "site_name", "building_name", "name"],
  "Full Address": ["address", "full_address", "complete_address", "property_address"],
  Street: ["street_address", "address_line_1", "street_name", "road", "avenue"],
  City: ["city_name", "municipality", "town"],
  County: ["county_name", "parish"],
  State: ["state_name", "province", "region"],
  "State Code": ["state_abbr", "state_abbreviation", "province_code"],
  "Postal Code": ["zip", "zip_code", "postal", "postcode"],
  Country: ["country_name", "nation"],
  Occupancy: ["occupancy_type", "use", "business_type", "property_use","Buisness Description"],
  "Nature of Occupancy": ["nature_of_use", "occupancy_nature", "use_type"],
  Construction: ["construction_type", "building_construction", "structure_type"],
  "Building Value": [
    "building value",
    "buildingvalue",
    "building_value",
    "building limit",
    "buildinglimit",
    "building_limit",
    "building coverage",
    "buildingcoverage",
    "building_coverage",
    "building sum insured",
    "building tiv",
    "building exposure",
    // From image - Buildings synonyms
    "real property",
    "hard cost",
    "property in open",
    "poi",
    "signs",
    "leasehold",
    "contingent building",
    "contingent property",
    "tanks",
    "fences",
    "light poles",
    "plants",
    "tenant improvements",
    "rr siding",
    "parking values",
    "docks & piers",
    "outdoor property",
    "offshore platform",
    "osp",
    "rolling stock",
    "railroads",
    "builders risk",
    "marshal swift cost",
    "ordinance or law",
    "improvements & betterments",
    "material damage",
    "tib",
    "tenant improvement and betterment",
  ],
  "Building Value 1": [
    "building value",
    "buildingvalue",
    "building_value",
    "building limit",
    "buildinglimit",
    "building_limit",
    "building coverage",
    "buildingcoverage",
    "building_coverage",
    "building sum insured",
    "building tiv",
    "building exposure",
    // From image - Buildings synonyms
    "real property",
    "hard cost",
    "property in open",
    "poi",
    "signs",
    "leasehold",
    "contingent building",
    "contingent property",
    "tanks",
    "fences",
    "light poles",
    "plants",
    "tenant improvements",
    "rr siding",
    "parking values",
    "docks & piers",
    "outdoor property",
    "offshore platform",
    "osp",
    "rolling stock",
    "railroads",
    "builders risk",
    "marshal swift cost",
    "ordinance or law",
    "improvements & betterments",
    "material damage",
    "tib",
    "tenant improvement and betterment",
  ],
  "Building Value 2": [
    "building value",
    "buildingvalue",
    "building_value",
    "building limit",
    "buildinglimit",
    "building_limit",
    "building coverage",
    "buildingcoverage",
    "building_coverage",
    "building sum insured",
    "building tiv",
    "building exposure",
    // From image - Buildings synonyms
    "real property",
    "hard cost",
    "property in open",
    "poi",
    "signs",
    "leasehold",
    "contingent building",
    "contingent property",
    "tanks",
    "fences",
    "light poles",
    "plants",
    "tenant improvements",
    "rr siding",
    "parking values",
    "docks & piers",
    "outdoor property",
    "offshore platform",
    "osp",
    "rolling stock",
    "railroads",
    "builders risk",
    "marshal swift cost",
    "ordinance or law",
    "improvements & betterments",
    "material damage",
    "tib",
    "tenant improvement and betterment",
  ],
  "Building Value 3": [
    "building value",
    "buildingvalue",
    "building_value",
    "building limit",
    "buildinglimit",
    "building_limit",
    "building coverage",
    "buildingcoverage",
    "building_coverage",
    "building sum insured",
    "building tiv",
    "building exposure",
    // From image - Buildings synonyms
    "real property",
    "hard cost",
    "property in open",
    "poi",
    "signs",
    "leasehold",
    "contingent building",
    "contingent property",
    "tanks",
    "fences",
    "light poles",
    "plants",
    "tenant improvements",
    "rr siding",
    "parking values",
    "docks & piers",
    "outdoor property",
    "offshore platform",
    "osp",
    "rolling stock",
    "railroads",
    "builders risk",
    "marshal swift cost",
    "ordinance or law",
    "improvements & betterments",
    "material damage",
    "tib",
    "tenant improvement and betterment",
  ],
  "Building Value 4": [
    "building value",
    "buildingvalue",
    "building_value",
    "building limit",
    "buildinglimit",
    "building_limit",
    "building coverage",
    "buildingcoverage",
    "building_coverage",
    "building sum insured",
    "building tiv",
    "building exposure",
    // From image - Buildings synonyms
    "real property",
    "hard cost",
    "property in open",
    "poi",
    "signs",
    "leasehold",
    "contingent building",
    "contingent property",
    "tanks",
    "fences",
    "light poles",
    "plants",
    "tenant improvements",
    "rr siding",
    "parking values",
    "docks & piers",
    "outdoor property",
    "offshore platform",
    "osp",
    "rolling stock",
    "railroads",
    "builders risk",
    "marshal swift cost",
    "ordinance or law",
    "improvements & betterments",
    "material damage",
    "tib",
    "tenant improvement and betterment",
  ],
  "Building Value 5":[
    "building value",
    "buildingvalue",
    "building_value",
    "building limit",
    "buildinglimit",
    "building_limit",
    "building coverage",
    "buildingcoverage",
    "building_coverage",
    "building sum insured",
    "building tiv",
    "building exposure",
    // From image - Buildings synonyms
    "real property",
    "hard cost",
    "property in open",
    "poi",
    "signs",
    "leasehold",
    "contingent building",
    "contingent property",
    "tanks",
    "fences",
    "light poles",
    "plants",
    "tenant improvements",
    "rr siding",
    "parking values",
    "docks & piers",
    "outdoor property",
    "offshore platform",
    "osp",
    "rolling stock",
    "railroads",
    "builders risk",
    "marshal swift cost",
    "ordinance or law",
    "improvements & betterments",
    "material damage",
    "tib",
    "tenant improvement and betterment",
  ],

  // Contents Values with comprehensive synonyms
  "Contents Value": [
    "contents value",
    "contentsvalue",
    "contents_value",
    "contents limit",
    "contentslimit",
    "contents_limit",
    "contents coverage",
    "contentscoverage",
    "contents_coverage",
    "contents sum insured",
    "contents tiv",
    "contents exposure",
    // From image - Contents synonyms
    "fine arts",
    "equipment",
    "vehicles",
    "furniture fittings",
    "retail",
    "computers",
    "mobile equipments",
    "edp",
    "electronics data processing",
    "bpp",
    "business personal property",
    "personal property",
    "rolling stock",
    "non-railroads",
    "valuable papers and records",
    "automobiles",
    "inland marine",
    "inventory",
    "stock",
    "throughput",
  ],
  "Contents Value 1": [
    "contents value",
    "contentsvalue",
    "contents_value",
    "contents limit",
    "contentslimit",
    "contents_limit",
    "contents coverage",
    "contentscoverage",
    "contents_coverage",
    "contents sum insured",
    "contents tiv",
    "contents exposure",
    // From image - Contents synonyms
    "fine arts",
    "equipment",
    "vehicles",
    "furniture fittings",
    "retail",
    "computers",
    "mobile equipments",
    "edp",
    "electronics data processing",
    "bpp",
    "business personal property",
    "personal property",
    "rolling stock",
    "non-railroads",
    "valuable papers and records",
    "automobiles",
    "inland marine",
    "inventory",
    "stock",
    "throughput",
  ],
  "Contents Value 2": [
    "contents value",
    "contentsvalue",
    "contents_value",
    "contents limit",
    "contentslimit",
    "contents_limit",
    "contents coverage",
    "contentscoverage",
    "contents_coverage",
    "contents sum insured",
    "contents tiv",
    "contents exposure",
    // From image - Contents synonyms
    "fine arts",
    "equipment",
    "vehicles",
    "furniture fittings",
    "retail",
    "computers",
    "mobile equipments",
    "edp",
    "electronics data processing",
    "bpp",
    "business personal property",
    "personal property",
    "rolling stock",
    "non-railroads",
    "valuable papers and records",
    "automobiles",
    "inland marine",
    "inventory",
    "stock",
    "throughput",
  ],
  "Contents Value 3": [
    "contents value",
    "contentsvalue",
    "contents_value",
    "contents limit",
    "contentslimit",
    "contents_limit",
    "contents coverage",
    "contentscoverage",
    "contents_coverage",
    "contents sum insured",
    "contents tiv",
    "contents exposure",
    // From image - Contents synonyms
    "fine arts",
    "equipment",
    "vehicles",
    "furniture fittings",
    "retail",
    "computers",
    "mobile equipments",
    "edp",
    "electronics data processing",
    "bpp",
    "business personal property",
    "personal property",
    "rolling stock",
    "non-railroads",
    "valuable papers and records",
    "automobiles",
    "inland marine",
    "inventory",
    "stock",
    "throughput",
  ],
  "Contents Value 4": [
    "contents value",
    "contentsvalue",
    "contents_value",
    "contents limit",
    "contentslimit",
    "contents_limit",
    "contents coverage",
    "contentscoverage",
    "contents_coverage",
    "contents sum insured",
    "contents tiv",
    "contents exposure",
    // From image - Contents synonyms
    "fine arts",
    "equipment",
    "vehicles",
    "furniture fittings",
    "retail",
    "computers",
    "mobile equipments",
    "edp",
    "electronics data processing",
    "bpp",
    "business personal property",
    "personal property",
    "rolling stock",
    "non-railroads",
    "valuable papers and records",
    "automobiles",
    "inland marine",
    "inventory",
    "stock",
    "throughput",
  ],
  "Contents Value 5": [
    "contents value",
    "contentsvalue",
    "contents_value",
    "contents limit",
    "contentslimit",
    "contents_limit",
    "contents coverage",
    "contentscoverage",
    "contents_coverage",
    "contents sum insured",
    "contents tiv",
    "contents exposure",
    // From image - Contents synonyms
    "fine arts",
    "equipment",
    "vehicles",
    "furniture fittings",
    "retail",
    "computers",
    "mobile equipments",
    "edp",
    "electronics data processing",
    "bpp",
    "business personal property",
    "personal property",
    "rolling stock",
    "non-railroads",
    "valuable papers and records",
    "automobiles",
    "inland marine",
    "inventory",
    "stock",
    "throughput",
  ],

  // Business Interruption Values with comprehensive synonyms
  "Business Interruption": [
    "business interruption",
    "businessinterruption",
    "business_interruption",
    "bi",
    "bi value",
    "bi limit",
    "bi coverage",
    "time element",
    "timeelement",
    "time_element",
    "loss of income",
    "lossofincome",
    "loss_of_income",
    "business income",
    "businessincome",
    "business_income",
    "bi sum insured",
    "bi tiv",
    "bi exposure",
    // From image - Business Interruption synonyms
    "extra expense",
    "net operating income",
    "soft cost",
    "contingent bi",
    "consequential loss",
    "budgeted rent",
    "loss of rent",
    "ordinary payroll",
    "dsu",
    "delay in start up cost",
    "tax and interest",
    "rental income",
    "variable margin estimates",
    "statutory fees",
    "professional fees",
    "demolitions",
    "spoilage",
    "insurable gross profit",
    "debris removal",
    "money in safe",
    "money in machine",
    "sales",
    "ancillary",
    "loss of income",
    "loi",
  ],
  "Business Interruption 1": [
    "business interruption",
    "businessinterruption",
    "business_interruption",
    "bi",
    "bi value",
    "bi limit",
    "bi coverage",
    "time element",
    "timeelement",
    "time_element",
    "loss of income",
    "lossofincome",
    "loss_of_income",
    "business income",
    "businessincome",
    "business_income",
    "bi sum insured",
    "bi tiv",
    "bi exposure",
    // From image - Business Interruption synonyms
    "extra expense",
    "net operating income",
    "soft cost",
    "contingent bi",
    "consequential loss",
    "budgeted rent",
    "loss of rent",
    "ordinary payroll",
    "dsu",
    "delay in start up cost",
    "tax and interest",
    "rental income",
    "variable margin estimates",
    "statutory fees",
    "professional fees",
    "demolitions",
    "spoilage",
    "insurable gross profit",
    "debris removal",
    "money in safe",
    "money in machine",
    "sales",
    "ancillary",
    "loss of income",
    "loi",
  ],
  "Business Interruption 2": [
    "business interruption",
    "businessinterruption",
    "business_interruption",
    "bi",
    "bi value",
    "bi limit",
    "bi coverage",
    "time element",
    "timeelement",
    "time_element",
    "loss of income",
    "lossofincome",
    "loss_of_income",
    "business income",
    "businessincome",
    "business_income",
    "bi sum insured",
    "bi tiv",
    "bi exposure",
    // From image - Business Interruption synonyms
    "extra expense",
    "net operating income",
    "soft cost",
    "contingent bi",
    "consequential loss",
    "budgeted rent",
    "loss of rent",
    "ordinary payroll",
    "dsu",
    "delay in start up cost",
    "tax and interest",
    "rental income",
    "variable margin estimates",
    "statutory fees",
    "professional fees",
    "demolitions",
    "spoilage",
    "insurable gross profit",
    "debris removal",
    "money in safe",
    "money in machine",
    "sales",
    "ancillary",
    "loss of income",
    "loi",
  ],
  "Business Interruption 3": [
    "business interruption",
    "businessinterruption",
    "business_interruption",
    "bi",
    "bi value",
    "bi limit",
    "bi coverage",
    "time element",
    "timeelement",
    "time_element",
    "loss of income",
    "lossofincome",
    "loss_of_income",
    "business income",
    "businessincome",
    "business_income",
    "bi sum insured",
    "bi tiv",
    "bi exposure",
    // From image - Business Interruption synonyms
    "extra expense",
    "net operating income",
    "soft cost",
    "contingent bi",
    "consequential loss",
    "budgeted rent",
    "loss of rent",
    "ordinary payroll",
    "dsu",
    "delay in start up cost",
    "tax and interest",
    "rental income",
    "variable margin estimates",
    "statutory fees",
    "professional fees",
    "demolitions",
    "spoilage",
    "insurable gross profit",
    "debris removal",
    "money in safe",
    "money in machine",
    "sales",
    "ancillary",
    "loss of income",
    "loi",
  ],
  "Business Interruption 4": [
    "business interruption",
    "businessinterruption",
    "business_interruption",
    "bi",
    "bi value",
    "bi limit",
    "bi coverage",
    "time element",
    "timeelement",
    "time_element",
    "loss of income",
    "lossofincome",
    "loss_of_income",
    "business income",
    "businessincome",
    "business_income",
    "bi sum insured",
    "bi tiv",
    "bi exposure",
    // From image - Business Interruption synonyms
    "extra expense",
    "net operating income",
    "soft cost",
    "contingent bi",
    "consequential loss",
    "budgeted rent",
    "loss of rent",
    "ordinary payroll",
    "dsu",
    "delay in start up cost",
    "tax and interest",
    "rental income",
    "variable margin estimates",
    "statutory fees",
    "professional fees",
    "demolitions",
    "spoilage",
    "insurable gross profit",
    "debris removal",
    "money in safe",
    "money in machine",
    "sales",
    "ancillary",
    "loss of income",
    "loi",
  ],
  "Business Interruption 5": [
    "business interruption",
    "businessinterruption",
    "business_interruption",
    "bi",
    "bi value",
    "bi limit",
    "bi coverage",
    "time element",
    "timeelement",
    "time_element",
    "loss of income",
    "lossofincome",
    "loss_of_income",
    "business income",
    "businessincome",
    "business_income",
    "bi sum insured",
    "bi tiv",
    "bi exposure",
    // From image - Business Interruption synonyms
    "extra expense",
    "net operating income",
    "soft cost",
    "contingent bi",
    "consequential loss",
    "budgeted rent",
    "loss of rent",
    "ordinary payroll",
    "dsu",
    "delay in start up cost",
    "tax and interest",
    "rental income",
    "variable margin estimates",
    "statutory fees",
    "professional fees",
    "demolitions",
    "spoilage",
    "insurable gross profit",
    "debris removal",
    "money in safe",
    "money in machine",
    "sales",
    "ancillary",
    "loss of income",
    "loi",
  ],
  "Sprinkler Type": ["sprinkler", "fire_protection", "sprinkler_system"],
  "Year Built": ["construction_year", "built_year", "year_constructed"],
  "No. of Buildings": ["building_count", "number_of_buildings", "buildings"],
  "No. of Stories": ["stories", "floors", "number_of_stories", "storeys"],
  "Square Footage": ["area", "floor_area", "square_feet", "sq_ft"],
  "Year Upgraded": ["renovation_year", "upgrade_year", "modernization_year"],
  "Roof Type": ["roof_material", "roofing", "roof_construction"],
  "Foundation Type": ["foundation", "foundation_material", "foundation_construction"],
  "Cladding Type": ["exterior_wall", "wall_material", "siding"],
  "Soft Story": ["soft_story_indicator", "weak_story"],
  "Tsunami Exposure": ["tsunami_risk", "tsunami_zone"],
  "Liquefaction Exposure": ["liquefaction_risk", "soil_liquefaction"],
}

export const OUTPUT_COLUMN_SEQUENCE = [
  // Keep this list for the final output ordering
  "Location Number",
  "Loc_Name_Final",
  "Street_Final",
  "City_Final",
  "County_Final",
  "State_Final",
  "Statecode_Final",
  "Postal_Final",
  "Country_Final",
  "Latitude",
  "Longitude",
  "Geospatial_Key",
  "Occupancy Scheme",
  "Occupancy Code",
  "Occupancy Confidence",
  "Construction Scheme",
  "Construction Code",
  "Construction Confidence",
  "Nature_of_Occupancy_Final",
  "Sprinkler_Type_Final",
  "Year_Built_Final",
  "No_of_Buildings_Final",
  "No_of_Stories_Final",
  "Square_Footage_Final",
  "Year_Upgraded_Final",
  "Roof_Type_Final",
  "Foundation_Type_Final",
  "Cladding_Type_Final",
  "Soft_Story_Final",
  "Tsunami_Exposure_Final",
  "Liquefaction_Exposure_Final",
  "Building_Value_Final",
  "Building_Value_1_Final",
  "Building_Value_2_Final",
  "Building_Value_3_Final",
  "Building_Value_4_Final",
  "Building_Value_5_Final",
  "Building_Value_Total_Final",
  "Contents_Value_Final",
  "Contents_Value_1_Final",
  "Contents_Value_2_Final",
  "Contents_Value_3_Final",
  "Contents_Value_4_Final",
  "Contents_Value_5_Final",
  "Contents_Value_Total_Final",
  "Business_Interruption_Final",
  "Business_Interruption_1_Final",
  "Business_Interruption_2_Final",
  "Business_Interruption_3_Final",
  "Business_Interruption_4_Final",
  "Business_Interruption_5_Final",
  "Business_Interruption_Total_Final",
  "Total_Insured_Value_Final",
  "Flood_Risk",
  "Seismic_Risk",
  "Wildfire_Risk",
]

export const HIGHLIGHTED_COLUMNS = [
  "Occupancy Scheme",
  "Occupancy Code",
  "Occupancy Confidence",
  "Construction Scheme",
  "Construction Code",
  "Construction Confidence",
  "Building_Value_Total_Final",
  "Contents_Value_Total_Final",
  "Business_Interruption_Total_Final",
  "Total_Insured_Value_Final",
  "Flood_Risk",
  "Seismic_Risk",
  "Wildfire_Risk",
]
