import type { ConstructionItem } from "./types"

export const constructionData: ConstructionItem[] = [
  // AIR Wood Construction (100-109)
  { scheme: "AIR", code: "100", description: "Unknown Construction" },
  { scheme: "AIR", code: "101", description: "Wood Frame - Modern" },
  { scheme: "AIR", code: "102", description: "Wood Frame - Light" },
  { scheme: "AIR", code: "103", description: "Wood Frame with Masonry Veneer" },
  { scheme: "AIR", code: "104", description: "Heavy Timber" },
  { scheme: "AIR", code: "105", description: "Wood Frame - Older" },
  { scheme: "AIR", code: "106", description: "Wood Frame - Post and Beam" },
  { scheme: "AIR", code: "107", description: "Wood Frame - Platform" },
  { scheme: "AIR", code: "108", description: "Wood Frame - Balloon" },
  { scheme: "AIR", code: "109", description: "Wood Frame - Other" },

  // AIR Masonry Construction (110-129)
  { scheme: "AIR", code: "110", description: "Masonry - General" },
  { scheme: "AIR", code: "111", description: "Masonry - Unspecified" },
  { scheme: "AIR", code: "112", description: "Adobe" },
  { scheme: "AIR", code: "113", description: "Rubble Stone" },
  { scheme: "AIR", code: "114", description: "Unreinforced Masonry Bearing Wall" },
  { scheme: "AIR", code: "115", description: "Unreinforced Masonry with Frame" },
  { scheme: "AIR", code: "116", description: "Reinforced Masonry" },
  { scheme: "AIR", code: "117", description: "Reinforced Masonry Shear Wall" },
  { scheme: "AIR", code: "118", description: "Masonry Infill" },
  { scheme: "AIR", code: "119", description: "Joisted Masonry" },
  { scheme: "AIR", code: "120", description: "Confined Masonry" },
  { scheme: "AIR", code: "121", description: "Brick Masonry" },
  { scheme: "AIR", code: "122", description: "Block Masonry" },
  { scheme: "AIR", code: "123", description: "Stone Masonry" },
  { scheme: "AIR", code: "124", description: "Masonry - Engineered" },
  { scheme: "AIR", code: "125", description: "Masonry - Non-Engineered" },
  { scheme: "AIR", code: "126", description: "Masonry - Seismic" },
  { scheme: "AIR", code: "127", description: "Masonry - Non-Seismic" },
  { scheme: "AIR", code: "128", description: "Masonry - Retrofitted" },
  { scheme: "AIR", code: "129", description: "Masonry - Other" },

  // AIR Concrete Construction (130-149)
  { scheme: "AIR", code: "130", description: "Concrete - General" },
  { scheme: "AIR", code: "131", description: "Reinforced Concrete" },
  { scheme: "AIR", code: "132", description: "Reinforced Concrete Shear Wall" },
  { scheme: "AIR", code: "133", description: "Reinforced Concrete Frame" },
  { scheme: "AIR", code: "134", description: "Reinforced Concrete - Ductile" },
  { scheme: "AIR", code: "135", description: "Reinforced Concrete - Non-Ductile" },
  { scheme: "AIR", code: "136", description: "Tilt-Up Concrete" },
  { scheme: "AIR", code: "137", description: "Precast Concrete" },
  { scheme: "AIR", code: "138", description: "Precast Concrete Shear Wall" },
  { scheme: "AIR", code: "139", description: "Precast Concrete Frame" },
  { scheme: "AIR", code: "140", description: "Concrete Block" },
  { scheme: "AIR", code: "141", description: "Concrete - Cast in Place" },
  { scheme: "AIR", code: "142", description: "Concrete - Post-Tensioned" },
  { scheme: "AIR", code: "143", description: "Concrete - Pre-Stressed" },
  { scheme: "AIR", code: "144", description: "Concrete - Lift Slab" },
  { scheme: "AIR", code: "145", description: "Concrete - Flat Slab" },
  { scheme: "AIR", code: "146", description: "Concrete - Waffle Slab" },
  { scheme: "AIR", code: "147", description: "Concrete - Two-Way Slab" },
  { scheme: "AIR", code: "148", description: "Concrete - One-Way Slab" },
  { scheme: "AIR", code: "149", description: "Concrete - Other" },

  // AIR Steel Construction (150-169)
  { scheme: "AIR", code: "150", description: "Steel - General" },
  { scheme: "AIR", code: "151", description: "Steel Frame" },
  { scheme: "AIR", code: "152", description: "Light Steel Frame" },
  { scheme: "AIR", code: "153", description: "Steel Frame - Braced" },
  { scheme: "AIR", code: "154", description: "Steel Frame - Unbraced" },
  { scheme: "AIR", code: "155", description: "Steel Frame - Eccentric Braced" },
  { scheme: "AIR", code: "156", description: "Steel Moment Frame" },
  { scheme: "AIR", code: "157", description: "Steel Frame - Welded" },
  { scheme: "AIR", code: "158", description: "Steel Frame - Bolted" },
  { scheme: "AIR", code: "159", description: "Steel Reinforced Concrete" },
  { scheme: "AIR", code: "160", description: "Steel Long Span" },
  { scheme: "AIR", code: "161", description: "Steel Truss" },
  { scheme: "AIR", code: "162", description: "Steel Joist" },
  { scheme: "AIR", code: "163", description: "Steel Deck" },
  { scheme: "AIR", code: "164", description: "Steel - Cold Formed" },
  { scheme: "AIR", code: "165", description: "Steel - Hot Rolled" },
  { scheme: "AIR", code: "166", description: "Steel - Composite" },
  { scheme: "AIR", code: "167", description: "Steel - Pre-Engineered" },
  { scheme: "AIR", code: "168", description: "Steel - Butler Building" },
  { scheme: "AIR", code: "169", description: "Steel - Other" },

  // AIR Mixed/Other Construction (170-199)
  { scheme: "AIR", code: "170", description: "Mixed Construction" },
  { scheme: "AIR", code: "171", description: "Steel and Concrete" },
  { scheme: "AIR", code: "172", description: "Steel and Masonry" },
  { scheme: "AIR", code: "173", description: "Wood and Steel" },
  { scheme: "AIR", code: "174", description: "Wood and Concrete" },
  { scheme: "AIR", code: "175", description: "Wood and Masonry" },
  { scheme: "AIR", code: "176", description: "Concrete and Masonry" },
  { scheme: "AIR", code: "177", description: "Hybrid Construction" },
  { scheme: "AIR", code: "178", description: "Composite Construction" },
  { scheme: "AIR", code: "179", description: "Multi-Material" },
  { scheme: "AIR", code: "180", description: "Modular Construction" },
  { scheme: "AIR", code: "181", description: "Prefabricated" },
  { scheme: "AIR", code: "182", description: "Panelized" },
  { scheme: "AIR", code: "183", description: "Insulated Concrete Form" },
  { scheme: "AIR", code: "184", description: "Structural Insulated Panel" },
  { scheme: "AIR", code: "185", description: "Rammed Earth" },
  { scheme: "AIR", code: "186", description: "Straw Bale" },
  { scheme: "AIR", code: "187", description: "Log Construction" },
  { scheme: "AIR", code: "188", description: "Earthbag" },
  { scheme: "AIR", code: "189", description: "Bamboo" },
  { scheme: "AIR", code: "190", description: "Alternative Materials" },
  { scheme: "AIR", code: "191", description: "Mobile Home" },
  { scheme: "AIR", code: "192", description: "Mobile Home - No Tie Down" },
  { scheme: "AIR", code: "193", description: "Mobile Home - Partial Tie Down" },
  { scheme: "AIR", code: "194", description: "Mobile Home - Full Tie Down" },
  { scheme: "AIR", code: "195", description: "Manufactured Home" },
  { scheme: "AIR", code: "196", description: "Modular Home" },
  { scheme: "AIR", code: "197", description: "Temporary Structure" },
  { scheme: "AIR", code: "198", description: "Tent Structure" },
  { scheme: "AIR", code: "199", description: "Other Construction" },
]
